### ISSUE TITLE
[XCode7.3 beta] Could not build Objective-C module 'GRDB'

### ISSUE THREAD

**Issue by morisk** [groue/GRDB.swift#24]
Cannot compile with Xcode 7.3 beta , 7.2.1 works just fines.

> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/module.modulemap:1:8: error: **redefinition** of module 'Compression'
module Compression [system] [extern_c] {
       ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/usr/include/module.modulemap:1:8: note: previously defined here
module Compression [system] [extern_c] {
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/module.modulemap:6:8: error: redefinition of module 'Darwin'
module Darwin [system] [extern_c] {
       ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/usr/include/module.modulemap:6:8: note: previously defined here
module Darwin [system] [extern_c] {
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/module.modulemap:1599:8: error: redefinition of module 'os'
module os [system] [extern_c] {
       ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/usr/include/module.modulemap:1599:8: note: previously defined here
module os [system] [extern_c] {
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/module.modulemap:1615:8: error: redefinition of module 'libkern'
module libkern [system] [extern_c] {
       ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/usr/include/module.modulemap:1615:8: note: previously defined here
module libkern [system] [extern_c] {
       ^
<unknown>:0: error: could not build Objective-C module 'GRDB'

/Pods/GRDB.swift/GRDB/Core/Support/CoreGraphics/CGFloat.swift

**Comment by groue** [comment]
Hello @morisk.

To build GRDB with Xcode 7.3 beta, you need to modify the GRDB file Support/module.modulemap by replacing Xcode.app with Xcode-beta.app.

**Comment by morisk** [comment]
Hello Groue, thanks for the answer.
But it not fix it. here is my modified header:
`framework module GRDB {
    umbrella header "GRDB.h"

    header "/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/sqlite3.h"

    export *
    module * { export * }
}
`
I must be missing something

**Comment by groue** [comment]
Did you try to clean everything? Is the error message the same, or do you have a new error message? Did you double-check if the file at the modified path actually exists?

I'm not in front of a computer but yet I'm 100% positive that the fix is in this particular path in this particular file, because I had the same issue a few days ago. So scratch this little itch it a little more, and you'll be right on tracks again.

**Comment by morisk** [comment]
I've added PR to fix this, i believe "MacOSX.platform" on iOS is what confused the compiler

**Comment by groue** [comment]
I won't accept the PR (see my [comment](https://github.com/groue/GRDB.swift/pull/25#issuecomment-185902770)). The module map works fine for both platforms on Xcode 7.2, the version of developers tools targeted by the master branch. Please feel free to share with experience with others here.

**Comment by groue** [comment]
The issue is closed, so you eventually managed to get your software working as expected?

**Comment by morisk** [comment]
I am no longer sure its an issue. Maybe after 73 release things be fixed. Currently I'm adding path to idk manually.

**Comment by groue** [comment]
OK @morisk. Don't hesitate coming back whenever you get stuck somewhere.

**Comment by sablib** [comment]
Same error with Xcode 7.3

**Comment by groue** [comment]
@sablib Just upgrade GRDB to the latest version
