### ISSUE TITLE
GRDB/Statement.swift:360: Fatal error: Statement is busy in GRDB 5.19.0

### ISSUE THREAD

**Issue by mallman** [groue/GRDB.swift#1155]
### What did you do?

I ran one of my project's perf tests.

### What did you expect to happen?

I expected it to run.

### What happened instead?

I received a fatal error:

> GRDB/Statement.swift:360: Fatal error: Statement is busy

This problem does not occur in 5.18.0. I suspect this problem was introduced by https://github.com/groue/GRDB.swift/pull/1139.

To be clearer, I get this error at https://github.com/groue/GRDB.swift/blob/v5.19.0/GRDB/Core/Statement.swift#L360.

This occurs when I fetch a `RowCursor`, call `.next()` and then `.forEach()`. If I do not call `.next()` but rather just `.forEach()`, the code works as expected.

### Environment

**GRDB flavor(s):** GRDBCustom
**GRDB version:** 5.19.0
**Installation method:** manual
**Xcode version:** 13.2.1 (13C100)
**Swift version:** 5.5.2-dev
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 12.1 (21C52)

**Comment by groue** [comment]
Hello @mallman,

Thanks for reporting this. Your diagnostic is correct. I did not expect that users would call next() and then forEach()!

All right, I've been too lazy 😅 I'll fix this.

Just for the sake of sharing a use case, and why do you call forEach after next?

**Comment by mallman** [comment]
> Just for the sake of sharing a use case, and if you have time, why do you call forEach after next?

I'm grouping row values into a data structure by a key defined by a query column. The query is ordered by that key column. I set the initial values with `rows.next()` (or return [] if the query has no initial value) and then loop through the rows with `rows.forEach()`, comparing the current key value to the initial value. When I reach a row with a new key value, I reinitialize the "initial" key value. Then I finish up with some duplicate code after `forEach` to handle that last row. It's awful. If this was a team or public project I would spend more time to make it lean, mean and sensible.

Now you have me rethinking this method. Damn.

**Comment by mallman** [comment]
Meanwhile, my perf tests are running up to 10% slower, but I don't have evidence this is caused by GRDB. I'm just whining. 😭

**Comment by groue** [comment]
I'll check this too! Just tell me which pattern seems slower: is it forEach, next, fetchAll? I've been tweaking statement iteration quite a bit, so your pair of eyes is quite helpful :)

**Comment by mallman** [comment]
Uh oh. No, really, I have no evidence this is GRDB's fault. I reverted all the way back to 5.16.0 and got the same perf regression in my code. Forget I mentioned it.

**Comment by groue** [comment]
Hm. Commit above is not a correct fix. I'm just making things more complex.

It's time to step back, and focus on the real goal. The only thing we need is making sure [transaction observers](https://github.com/groue/GRDB.swift/blob/master/README.md#transactionobserver-protocol) are notified of deletions when the app executes `DELETE FROM table`.

This SQL statement, by default, triggers the [truncate optimization](https://www.sqlite.org/lang_delete.html#truncateopt). The truncate optimization prevents [Data Change Notification Callbacks](https://www.sqlite.org/c3ref/update_hook.html) from firing. Without change notification callbacks, transaction observers are not notified of deletions. And ValueObservation and friends can't do their job.

**Comment by mallman** [comment]
The RDBMes I've seen implement the "truncate optimization" with the `TRUNCATE` statement. In these systems, if you want to truncate a table you run `TRUNCATE <table>`. If you want to delete the rows of a table you run `DELETE FROM <table>`. Why did SQLite decide to make `DELETE FROM` more complicated by adding a special case? One could argue they broke their own change listener interface, but maybe that didn't exist when this functionality was "optimized".

I can see it's doubly frustrating because there's no simple way to opt-out. Why is this so difficult?

Have you messaged the SQLite forum for help? Am I getting at the crux of the issue?

**Comment by mallman** [comment]
BTW, I know SQLite is not an RDBMS. The analogy works despite that.

**Comment by groue** [comment]
Don't be too harsh with SQLite ;-) Now you're right, this truncate optimization is a PITA in the context of database observation.

I'm not sure SQLite will improve on this side, at least not until I can convince its author that observation is an important use case. Last time we discussed this topic, [he was not thrilled](https://www.mail-archive.com/sqlite-users@mailinglists.sqlite.org/msg116104.html) by [the observation technique used by GRDB](https://github.com/groue/GRDB.swift/blob/v5.19.0/GRDB/Core/TransactionObserver.swift#L79):

> You have hacked around this security feature

😅

**Comment by groue** [comment]
OK, #1162 fixes it.

> The problem with cursors is that users can be nasty:
> 
> ```swift
> let deletedIds = try Int64.fetchCursor(db, sql: "DELETE FROM table RETURNING id")
> 
> // Delete some rows (maybe even truncate, I don't know), and get the id of the first deleted row.
> _ = try deletedIds.next()
> 
> // Lol, observe deletions now
> let observer = MyDeletionObserver()
> db.add(transactionObserver: observer)
> 
> // Either the observer is notified of deletion. Or fatalError. Or throw.
> _ = try deletedIds.next()
> ```

Now I better understand the expected behavior of this sample code, because SQLite can only prevent the truncate optimization during the compilation of the statement. Here, the cursor (and its statement) are instantiated before the database observation has started, so the truncate optimization is not prevented: the observer should not expect to be notified of anything. This is just how SQLite behaves.

**Comment by mallman** [comment]
Thanks for the great work on this!

**Comment by groue** [comment]
The fix has shipped in v5.20.0
